export const ACTIONS = {
    ORDER_TABLE_INIT: 'ORDER_TABLE_INIT',
    WEB_SOCKET_ONOPEN: 'WEB_SOCKET_ONOPEN',
    WEB_SOCKET_CLOSE: 'WEB_SOCKET_CLOSE',
    ORDER_TABLE_DATA_RECEIVED: 'ORDER_TABLE_DATA_RECEIVED'
}

export const ACTION_STATUS = {
    SUCCESS: 'SUCCESS'
}

export function noOp() {

}